spring.application.name=core

server.port=8080

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/kaspi_travel
spring.r2dbc.username=kaspidev
spring.r2dbc.password=kaspipassword

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.kafka.boostrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.sql.init.mode=always

# --- НАСТРОЙКИ CIRCUIT BREAKER ---
# Имя нашего предохранителя: flightProvider
# Анализируем последние 5 запросов
resilience4j.circuitbreaker.instances.flightProvider.sliding-window-size=5
# Если 50% из них упали (т.е. 3 из 5) - ВЫБИВАЕМ ПРОБКИ (Open State)
resilience4j.circuitbreaker.instances.flightProvider.failure-rate-threshold=50
# Ждем 30 секунд перед тем, как снова попробовать послать запрос
resilience4j.circuitbreaker.instances.flightProvider.wait-duration-in-open-state=30s
# Пропускаем 3 тестовых запроса через 30 секунд для проверки "ожил ли пациент"
resilience4j.circuitbreaker.instances.flightProvider.permitted-number-of-calls-in-half-open-state=3

# --- НАСТРОЙКИ МОНИТОРИНГА (ACTUATOR) ---
# Открываем доступ к проверке здоровья, метрикам и состоянию предохранителей
management.endpoints.web.exposure.include=health,metrics,circuitbreakers
# Показывать подробности (например, пинг до базы данных и Kafka)
management.endpoint.health.show-details=always