server.port=8082

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/kaspi_travel
spring.r2dbc.username=kaspidev
spring.r2dbc.password=kaspipassword

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.sql.init.mode=always
