server.port=8082
spring.application.name=booking-orchestrator

# База данных PostgreSQL (R2DBC)
spring.r2dbc.url=r2dbc:postgresql://localhost:5433/travel_db
spring.r2dbc.username=travel_user
spring.r2dbc.password=travel_password
# Говорим Spring Boot автоматически запустить schema.sql
spring.sql.init.mode=always

# Подключение к Kafka
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
